spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:15940898}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
  batch:
    jdbc:
      initialize-schema: ${SPRING_BATCH_JDBC_INITIALIZE_SCHEMA:always}
    job:
      enabled: ${SPRING_BATCH_JOB_ENABLED:false}

logging:
  level:
    root: INFO
    org.springframework.batch: TRACE
    org.springframework.jdbc: TRACE
    org.springframework.data.redis: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.example.Spring.batch.Training: TRACE